### ISSUE TITLE
Add linux

### ISSUE THREAD

**Issue by PhoenixSys** [cert-ee/cuckoo3#53] opened 2023-07-06 17:18 UTC
Hi .
How can i add linux vm to cuckoo ? I need it please help me

**Comment by Cryss76** [comment] 2023-07-06 17:29
You can't. Take a look at the [docs](https://github.com/cert-ee/cuckoo3/blob/main/docs/src/introduction/cuckoo.md)

**Comment by PhoenixSys** [comment] 2023-07-06 18:21
> You can't. Take a look at the [docs](https://github.com/cert-ee/cuckoo3/blob/main/docs/src/introduction/cuckoo.md)

Ok , but i can use ubuntu vm in cuckoo 2 , why is not possible in cuckoo 3 ??

**Comment by inventoramin** [comment] 2023-07-06 18:28
> > You can't. Take a look at the [docs](https://github.com/cert-ee/cuckoo3/blob/main/docs/src/introduction/cuckoo.md)
> 
> Ok , but i can use ubuntu vm in cuckoo 2 , why is not possible in cuckoo 3 ??

exactly, in [this](https://cuckoo.readthedocs.io/en/latest/installation/guest/linux/) it is possible. does it need to be implemented by you or we can do it by ourself?

**Comment by Cryss76** [comment] 2023-08-01 13:31
As this issue was mentioned again in #59: Cuckoo3 doesn't support Linux as an analysis target and here is why:

Cuckoo3 is a complete reimplementation of the Cuckoo Project and works quite differently than older versions. Therefore old docs of Cuckoo2 don't apply. (Also Cuckoo3 doesn't have feature parity with Cuckoo2, at this point)

The main reason is the monitor of Cuckoo3, which is a windows driver and collects the actual behavioral info for the analysis. Also the processing modules seems to be written with the windows driver monitor in mind.

@amadisson is there linux support planed?

**Comment by rkivistik** [comment] 2024-07-02 13:44
@Cryss76 Linux support is planned.
Once we have our roadmap set, we can shed some more light when it might happen.

**Comment by cert-ee-raidar** [comment] 2024-09-14 10:27
This will be covered in #119 
Closing the issue as duplicate now.

**Closed by cert-ee-raidar** 2024-09-14 10:27 UTC
Labels: enhancement

**Comment by cert-ee-raidar** [comment] 2024-09-14 10:30
Duplicate of #119

**Comment by cert-ee-raidar** [comment] 2024-09-14 10:30
Closing the issue.
