### ISSUE TITLE
httpreplay.exceptions.UnknownHttpEncoding: xpress

### ISSUE THREAD

**Issue by GhostRock37** [cert-ee/cuckoo3#92] opened 2024-06-19 16:06 UTC
**Describe the bug**
when i start an analysis, the analysis is going to an error . the analysis don't produce results:

**To Reproduce**
Steps to reproduce the behavior: submit an analysis ( batch file or url ...)

**Expected behavior**
![image](https://github.com/cert-ee/cuckoo3/assets/25516319/fce3f55e-43ec-4176-8805-9ec9e84a14c1)

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.0, Ubuntu 24.04
Python 3.11.9
HTTPReplay  1.0.1
```


**The log, error, files etc can be found at:**

2024-06-19 17:36:37 ERROR [cuckoo.processing.worker]: Failure during processing. error=Failed to run plugin Pcapreader. xpress task_id=20240619-SHL4SU_1
Traceback (most recent call last):
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/worker.py", line 197, in _run_processing_instances
    data = instance.start()
           ^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/post/network.py", line 312, in start
    for flow, ts, proto, sent, recv in r.process():
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/reader.py", line 130, in process
    self.tcp and self.tcp.process(ts, ip, packet)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 143, in process
    s.process(ts, tcp, to_server)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 423, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 342, in state_conn
    self.parent.handle(
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 724, in handle
    while self.states[self.state](self, s, ts):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 678, in state_stream
    self.parent.handle(
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 285, in handle
    super(HttpsProtocol, self).handle(s, ts, protocol, sent, recv, tlsinfo)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 262, in handle
    s, ts, protocols[protocol], req, self.parse_response(ts, recv),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 198, in parse_response
    raise UnknownHttpEncoding(content_encoding)
httpreplay.exceptions.UnknownHttpEncoding: xpress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/worker.py", line 231, in _handle_processing
    _run_processing_instances(processing_instances, ctx)
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/worker.py", line 205, in _run_processing_instances
    raise PluginError(
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/worker.py", line 197, in _run_processing_instances
    data = instance.start()
           ^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/cuckoo3/processing/cuckoo/processing/post/network.py", line 312, in start
    for flow, ts, proto, sent, recv in r.process():
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/reader.py", line 130, in process
    self.tcp and self.tcp.process(ts, ip, packet)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 143, in process
    s.process(ts, tcp, to_server)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 423, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 342, in state_conn
    self.parent.handle(
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 724, in handle
    while self.states[self.state](self, s, ts):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/transport.py", line 678, in state_stream
    self.parent.handle(
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 285, in handle
    super(HttpsProtocol, self).handle(s, ts, protocol, sent, recv, tlsinfo)
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 262, in handle
    s, ts, protocols[protocol], req, self.parse_response(ts, recv),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandboxuser/Documents/cuckoonew/venv/lib/python3.11/site-packages/httpreplay/protoparsers.py", line 198, in parse_response
    raise UnknownHttpEncoding(content_encoding)
cuckoo.processing.errors.PluginError: Failed to run plugin Pcapreader. xpress
2024-06-19 17:36:37 ERROR [cuckoo.control]: Task post stage failed. task_id=20240619-SHL4SU_1
```

![image](https://github.com/cert-ee/cuckoo3/assets/25516319/ed22b2f7-b237-4eb5-a0ae-81460ede2dcb)

**Comment by Cryss76** [comment] 2024-09-12 10:03
This is a duplicate of issue #50. You can close this one @cert-ee-raidar

**Closed** 2024-09-12 10:07 UTC
