### ISSUE TITLE
Cuckoo database (cuckoodb) requires migration(s)

### ISSUE THREAD

**Issue by HadyElMaageny** [cert-ee/cuckoo3#93] opened 2024-06-20 05:00 UTC
I have installed cuckoo 3, but when I call cuckoo command I get this error and I can't fix it:
ERROR [cuckoo.common.log]: Failure during Cuckoo startup: Cuckoo database (cuckoodb) requires migration(s). sqlite:////home/hady/.cuckoocwd/cuckoo.db. Found version: 'No version table'. Latest version: ''. 
Stopping Cuckoo..
Failure during Cuckoo startup: Cuckoo database (cuckoodb) requires migration(s). sqlite:////home/hady/.cuckoocwd/cuckoo.db. Found version: 'No version table'. Latest version: ''.

**Comment by rkivistik** [comment] 2024-07-02 09:59
Seems like your database file is corrupt. 
Try renaming the database file and Cuckoo will recreate it on startup.
When a new database is created on startup and Cuckoo starts after that, then the issue is faulty database.
If you need the data from your not working database, you can use sql tools to try to recover the data.

**Comment by rkivistik** [comment] 2024-07-08 12:50
@HadyElMaageny 
Sorry for the slightly misguided advice on my part.
Please run `cuckoomigrate database all` in your cuckoo3 folder (where install.sh is located).
Please do let me know if it worked.

**Comment by HadyElMaageny** [comment] 2024-07-08 15:24
thanks it works
but I get this error
2024-07-08 18:21:36 INFO  [cuckoo.startup]: Starting Cuckoo.
cwd=/home/hady/.cuckoocwd
2024-07-08 18:21:36 INFO  [cuckoo.startup]: Loading configurations
2024-07-08 18:21:36 INFO  [cuckoo.node.resultserver]: Changed maximum file
descriptors to hard limit for current process. newmax=1048576
2024-07-08 18:21:36 INFO  [cuckoo.node.resultserver]: Started resultserver.
listen_ip=169.254.10.50 listen_port=2042
2024-07-08 18:21:36 ERROR [cuckoo.common.log]: Failure during Cuckoo
startup: Machinery loading failure: Loading of machinery module qemu
failed. QEMU memory snapshot of machine 'example1' is of unknown filetype
or compressed with unsupported compression. Snapshot can be uncompressed or
compressed with lz4 or gzip.
Stopping Cuckoo..
2024-07-08 18:21:36 INFO  [cuckoo.node.resultserver]: Stopping
resultserver..
Failure during Cuckoo startup: Machinery loading failure: Loading of
machinery module qemu failed. QEMU memory snapshot of machine 'example1' is
of unknown filetype or compressed with unsupported compression. Snapshot
can be uncompressed or compressed with lz4 or gzip.

the snapshot is found at path
/var/lib/libvirt/qemu/snapshot/win10-2/snapshot3.xml

**Comment by rkivistik** [comment] 2024-07-08 15:44
Follow the `Machine adding command` in the documentation - https://cuckoo-hatch.cert.ee/static/docs/installation/vmcreation/ and your `$CWD/conf/machineries/qemu.yaml` should be populated with correct information

**Comment by HadyElMaageny** [comment] 2024-07-08 16:08
I have followed it but I can't get  The filepath to the machine memory
snapshot can you help me, please ?

**Comment by Cryss76** [comment] 2024-07-08 16:58
Cuckoo has two machinery modules regarding qemu:

- qemu: Which is for using qemu and kvm **without** libvirt. This is what you are using atm.
- libvirt: This one is confusing as it is called kvm and kvm libvirt on the docs  and is for using qemu/kvm **with** libvirt. @rkivistik resolving this ambiguity would be a nice improvement for the docs.

> the snapshot is found at path
/var/lib/libvirt/qemu/snapshot/win10-2/snapshot3.xml

@HadyElMaageny This isn't the snapshot. This is a description/config file of the actual snapshot. Because of this I believe you're using libvirt for your VMs. Therefore the problem is that you are trying to use the qemu module for libvirt stuff.

Change cuckoo to use the libvirt module and configure it to fix this.

**Comment by rkivistik** [comment] 2024-07-08 17:35
@Cryss76 I will look into it to resolve the ambiguity, thank you for pointing it out.
@HadyElMaageny please open a new issue if the problem persists and above suggestion does not work.
This issue has been resolved.

**Closed by rkivistik** 2024-07-08 17:35 UTC
Labels: setup

**Comment by cert-ee-raidar** [comment] 2024-07-09 08:57
@HadyElMaageny 
If you need further assistance with your setup, please email us at cuckoo3[at]cert.ee and ask to be added to our Cuckoo3 chat.

**Comment by HadyElMaageny** [comment] 2024-07-22 20:22
Is There an API to use this site https://cuckoo.cert.ee/ to Post a sample
and get the analysis report ?
