### ISSUE TITLE
Export behavioral analysis: processes and API calls, report.json

### ISSUE THREAD

**Issue by samybtt** [cert-ee/cuckoo3#94] opened 2024-07-03 09:59 UTC
Hello, is it possible to export the behavioral analysis information with the different API calls and their arguments for each process ? The same kind of information we could find on the `report.json` with Cuckoo 2.

If not, will it be available in the future ?

Thank you!

Here is a snippet from the `report.json` generated with Cuckoo 2 for one example, to illustrate this kind of information.
![image](https://github.com/cert-ee/cuckoo3/assets/48533654/a0541e16-7cb4-46d9-ac2c-47284c2ee07b)

**Comment by rkivistik** [comment] 2024-07-03 11:56
Hey @samybtt 
At this moment we do not have the export functionality in Cuckoo3.
It is planned however so stay tuned for our roadmap to get a rough estimate of when it might happen.

**Comment by cert-ee-raidar** [comment] 2024-09-14 10:32
Duplicate of #107

**Comment by cert-ee-raidar** [comment] 2024-09-14 10:33
Closing the issue as this is now in our roadmap under appropriate issue

**Closed by cert-ee-raidar** 2024-09-14 10:33 UTC
Labels: enhancement
